# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1aa7f3b4a8a6d72961ae62ce371f8b2aea3f7701af3e2e70c2b24f0327f038abbf4494923fe8ec2f66b5357b128d62e6dfb5175fed523d535005b9b2c0d380c

test:
  secret_key_base: 474570077fc4001ce3822f73d008f414e8bd9545cf4180cfbbbf8e15d0a5e62b0c2b68880d2d2187390324c47bfbb0284df5aacbb5b6a310d3a4949e4fc1e28f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
